### ISSUE TITLE
Performance Suggestion for Jmespath Caching

### ISSUE THREAD

**Issue by satish860** [jdevillard/JmesPath.Net#17] opened 2019-05-13 11:04 UTC
Context: I have a scenario to evaluate multiple Jmespath on a single device context.  As of the Jtoken is created for every Json per Rule.  

E.g., On a JSON Document, I need to run 150000 Jmespath.   Also, I need a way to run it on the Multiple documents based on the Request.  

If there is a way provided to improve the  JToken or reuse the Jtoken and provide the expression which I can cache will be helpful.

I can provide PR for the same.

**Comment by springcomp** [comment] 2019-05-13 20:31
Please do.

I was thinking along the same lines initially, with a call to a `Compile` method that would return a cacheable expression. I'm interested in working with you on this.

**Comment by satish860** [comment] 2019-05-14 04:34
Cool, Then will work on that and provide a PR.

**Comment by springcomp** [comment] 2019-05-14 05:15
We do not, the unfortunately.

I was looking at the code more since you expressed your concern. Please, note that the override using a JToken is deprecated, so should not be relied upon going forward.

I see that we return the parsed expression that can live in memory. You could keep that and use it for each iteration. Isn't that sufficient for your needs ?

**Comment by springcomp** [comment] 2019-05-14 05:19
If you do performance work, please include reproducible benchmarks. Have you heard of [https://github.com/dotnet/BenchmarkDotNet](BenchmarkDotNet)

**Comment by satish860** [comment] 2019-05-15 05:28
@springcomp Yes, I am using BenchMarkDotNet. With expression and token, I am seeing a good improvement

![image](https://user-images.githubusercontent.com/817360/57750520-3ab29c00-7700-11e9-88ec-0327c78c0dd5.png)

Will add Benchmark project and provide results

**Comment by springcomp** [comment] 2019-05-15 05:33
Awsome. Thank you!

**Comment by springcomp** [comment] 2022-02-26 07:38
The parser already supports parsing once and evaluating many times.
Closing this issue.

**Closed by springcomp** 2022-02-26 07:38 UTC
